"""
Generated by generator/generator.py - 2023-09-02 20:23:22.581947
"""
import pytest


@pytest.fixture()
def device_fixture_response():
    return {
        "locationID": 123456,
        "displayedOutdoorHumidity": 51,
        "vacationHold": {"enabled": False},
        "currentSchedulePeriod": {"day": "Saturday", "period": "P5"},
        "scheduleCapabilities": {
            "availableScheduleTypes": ["None", "Geofenced", "TimedEmea"],
            "schedulableFan": False,
        },
        "scheduleType": {"scheduleType": "Timed", "scheduleSubType": "EMEA"},
        "dhwZone": {
            "deviceId": "LCC-DHW-123456789ABCD",
            "deviceClass": "DHW",
            "deviceType": "DHW",
            "dhw": {
                "dhwState": "Off",
                "status": "TemporaryHold",
                "boostDuration": 0,
                "vacationHold": {"enabled": True},
                "geoBoostEnabled": False,
                "nextPeriodTime": "06: 00: 00",
            },
            "currentSchedulePeriod": {"day": "Saturday", "period": "P2"},
        },
        "scheduleStatus": "Pause",
        "allowedTimeIncrements": 10,
        "settings": {
            "hardwareSettings": {"brightness": 4, "maxBrightness": 5},
            "temperatureMode": {"air": False},
            "specialMode": {},
            "devicePairingEnabled": True,
        },
        "deviceOsVersion": "T6H700RW4011",
        "deviceClass": "Thermostat",
        "deviceType": "Thermostat",
        "deviceID": "LCC-00A01AB1ABCD",
        "userDefinedDeviceName": "Thermostat",
        "name": "Thermostat",
        "isAlive": True,
        "isUpgrading": False,
        "isProvisioned": True,
        "macID": "00A01AB1ABCD",
        "deviceSettings": {},
        "service": {"mode": "Up"},
        "deviceRegistrationDate": "2023-09-02T15: 40: 08.7333333",
        "dataSyncStatus": "Completed",
        "deviceSerialNo": "12312312312312",
        "units": "Celsius",
        "indoorTemperature": 21,
        "outdoorTemperature": 22,
        "allowedModes": ["Heat", "Off"],
        "deadband": 0,
        "hasDualSetpointStatus": False,
        "minHeatSetpoint": 5,
        "maxHeatSetpoint": 35,
        "minCoolSetpoint": -18,
        "maxCoolSetpoint": -18,
        "changeableValues": {
            "mode": "Off",
            "heatSetpoint": 16,
            "coolSetpoint": 29.5,
            "thermostatSetpointStatus": "PermanentHold",
            "heatCoolMode": "Heat",
            "endHeatSetpoint": None,
            "endCoolSetpoint": None,
        },
        "operationStatus": {
            "mode": "EquipmentOff",
            "fanRequest": False,
            "circulationFanRequest": False,
        },
        "deviceModel": "T5-T6",
    }
